name: Practice Action

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
      

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: check
        run: echo "${{ github.event.inputs.version }}"

      - name: Install Python
        uses: actions/setup-python@v5

      - name: Test
        run: python test.py
